# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev-izzeeeey" ]
  pull_request:
    branches: [ "dev-izzeeeey" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: debian-bookworm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to initialize..."
          sleep 10  # Adjust this duration based on your application's startup time

      - name: Stop and remove containers
        if: always()
        run: docker-compose down
